// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"WMSS/liquidation/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: HealthCheckHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/liquidation/logs",
				Handler: GetLiquidationLogsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/liquidation/quotation/latest",
				Handler: GetLatestNetValuesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/liquidation/quotation/update",
				Handler: QuotationUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/liquidation/rollback",
				Handler: LiquidationRollbackHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/liquidation/steps/statistics",
				Handler: GetLiquidationStepStatisticsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/liquidation/trading-day/current",
				Handler: GetCurrentTradingDayHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/liquidation/trading-day/init",
				Handler: TradingDayInitHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/liquidation/transaction/confirm",
				Handler: TransactionConfirmHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/liquidation/transaction/pending",
				Handler: GetPendingTransactionsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/liquidation/transaction/retry",
				Handler: RetryFailedTransactionsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)
}
