// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type BaseResponse struct {
	Code    int64       `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type ConfirmRequest struct {
	ConfirmationDate string   `json:"confirmationDate" validate:"required"`
	OperatorId       string   `json:"operatorId" validate:"required"`
	ApplicationIds   []string `json:"applicationIds,optional"` // 可选，指定处理哪些申请
	BatchSize        int64    `json:"batchSize,optional,default=100" validate:"min=1,max=1000"`
}

type ConfirmResponse struct {
	ConfirmationDate   string              `json:"confirmationDate"`
	TotalProcessed     int64               `json:"totalProcessed"`
	SuccessCount       int64               `json:"successCount"`
	FailedCount        int64               `json:"failedCount"`
	ConfirmationIds    []string            `json:"confirmationIds"`
	FailedApplications []FailedApplication `json:"failedApplications,optional"`
	TotalFees          float64             `json:"totalFees"`
}

type FailedApplication struct {
	ApplicationId string `json:"applicationId"`
	ErrorReason   string `json:"errorReason"`
	CustomerId    string `json:"customerId"`
	ProductId     string `json:"productId"`
}

type PageResponse struct {
	Total   int64       `json:"total"`
	Records interface{} `json:"records"`
	Page    int64       `json:"page"`
	Size    int64       `json:"size"`
}

type PurchaseRequest struct {
	CustomerId    string  `json:"customerId" validate:"required"`
	ProductId     string  `json:"productId" validate:"required"`
	CardId        int64   `json:"cardId" validate:"required"`
	Amount        float64 `json:"amount" validate:"required,gt=0"`
	OperatorId    string  `json:"operatorId" validate:"required"`
	RiskConfirmed bool    `json:"riskConfirmed,optional"` // 风险不匹配时客户确认
}

type PurchaseResponse struct {
	ApplicationId   string  `json:"applicationId"`
	ApplicationDate string  `json:"applicationDate"`
	ApplicationTime string  `json:"applicationTime"`
	ExpectedDate    string  `json:"expectedDate"`
	Status          string  `json:"status"`
	Amount          float64 `json:"amount"`
	PurchaseFee     float64 `json:"purchaseFee,optional"`
	NetAmount       float64 `json:"netAmount,optional"`
}

type RedemptionRequest struct {
	CustomerId string  `json:"customerId" validate:"required"`
	ProductId  string  `json:"productId" validate:"required"`
	CardId     int64   `json:"cardId" validate:"required"`
	Shares     float64 `json:"shares" validate:"required,gt=0"`
	OperatorId string  `json:"operatorId" validate:"required"`
}

type RedemptionResponse struct {
	ApplicationId   string  `json:"applicationId"`
	ApplicationDate string  `json:"applicationDate"`
	ApplicationTime string  `json:"applicationTime"`
	ExpectedDate    string  `json:"expectedDate"`
	Status          string  `json:"status"`
	Shares          float64 `json:"shares"`
	ExpectedAmount  float64 `json:"expectedAmount,optional"`
	RedemptionFee   float64 `json:"redemptionFee,optional"`
}

type TransactionDetail struct {
	ApplicationId    string  `json:"applicationId"`
	Type             string  `json:"type"`
	CustomerId       string  `json:"customerId"`
	CustomerName     string  `json:"customerName"`
	ProductId        string  `json:"productId"`
	ProductName      string  `json:"productName"`
	ApplicationDate  string  `json:"applicationDate"`
	ApplicationTime  string  `json:"applicationTime"`
	ConfirmationDate string  `json:"confirmationDate,optional"`
	Status           string  `json:"status"`
	OperatorId       string  `json:"operatorId"`
	Amount           float64 `json:"amount,optional"`
	PurchaseFee      float64 `json:"purchaseFee,optional"`
	NetAmount        float64 `json:"netAmount,optional"`
	ConfirmedShares  float64 `json:"confirmedShares,optional"`
	Shares           float64 `json:"shares,optional"`
	ExpectedAmount   float64 `json:"expectedAmount,optional"`
	RedemptionFee    float64 `json:"redemptionFee,optional"`
	HoldingPeriod    int64   `json:"holdingPeriod,optional"`
	ConfirmedAmount  float64 `json:"confirmedAmount,optional"`
	NetValue         float64 `json:"netValue,optional"` // 确认时使用的净值
	ConfirmationId   string  `json:"confirmationId,optional"`
	CreateTime       string  `json:"createTime"`
	UpdateTime       string  `json:"updateTime"`
}

type TransactionQuery struct {
	ApplicationId string `form:"applicationId,optional"`
	CustomerId    string `form:"customerId,optional"`
	ProductId     string `form:"productId,optional"`
	StartDate     string `form:"startDate,optional"`
	EndDate       string `form:"endDate,optional"`
	Type          string `form:"type,optional" validate:"omitempty,oneof=PURCHASE REDEMPTION"`
	Status        string `form:"status,optional"`
	Page          int64  `form:"page,optional,default=1"`
	Size          int64  `form:"size,optional,default=20"`
}

type TransactionRecord struct {
	ApplicationId    string  `json:"applicationId"`
	Type             string  `json:"type"` // PURCHASE, REDEMPTION
	CustomerId       string  `json:"customerId"`
	CustomerName     string  `json:"customerName"`
	ProductId        string  `json:"productId"`
	ProductName      string  `json:"productName"`
	Amount           float64 `json:"amount,optional"`
	Shares           float64 `json:"shares,optional"`
	ApplicationDate  string  `json:"applicationDate"`
	ApplicationTime  string  `json:"applicationTime"`
	ConfirmationDate string  `json:"confirmationDate,optional"`
	Status           string  `json:"status"`
	OperatorId       string  `json:"operatorId"`
}
