// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type BaseResponse struct {
	Code    int64       `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type CancelRequest struct {
	ApplicationId   string `json:"applicationId" validate:"required"`                             // 申请编号
	TransactionType string `json:"transactionType" validate:"required,oneof=PURCHASE REDEMPTION"` // 交易类型：PURCHASE-申购，REDEMPTION-赎回
	OperatorId      string `json:"operatorId" validate:"required"`                                // 操作员ID
	Reason          string `json:"reason,optional"`                                               // 撤回原因
}

type CancelResponse struct {
	ApplicationId   string  `json:"applicationId"`           // 申请编号
	TransactionType string  `json:"transactionType"`         // 交易类型
	OriginalStatus  string  `json:"originalStatus"`          // 原始状态
	NewStatus       string  `json:"newStatus"`               // 新状态
	CancelTime      string  `json:"cancelTime"`              // 撤回时间
	Reason          string  `json:"reason,optional"`         // 撤回原因
	RefundAmount    float64 `json:"refundAmount,optional"`   // 退款金额（申购撤回时）
	UnfrozenShares  float64 `json:"unfrozenShares,optional"` // 解冻份额（赎回撤回时）
}

type ConfirmRequest struct {
	ConfirmationDate string   `json:"confirmationDate" validate:"required"`
	OperatorId       string   `json:"operatorId" validate:"required"`
	ApplicationIds   []string `json:"applicationIds,optional"` // 可选，指定处理哪些申请
	BatchSize        int64    `json:"batchSize,optional,default=100" validate:"min=1,max=1000"`
}

type ConfirmResponse struct {
	ConfirmationDate   string              `json:"confirmationDate"`
	TotalProcessed     int64               `json:"totalProcessed"`
	SuccessCount       int64               `json:"successCount"`
	FailedCount        int64               `json:"failedCount"`
	ConfirmationIds    []string            `json:"confirmationIds"`
	FailedApplications []FailedApplication `json:"failedApplications,optional"`
	TotalFees          float64             `json:"totalFees"`
}

type CustomerProductPosition struct {
	ProductId       string  `json:"productId"`       // 产品标识
	ProductName     string  `json:"productName"`     // 产品名称
	ProductType     string  `json:"productType"`     // 产品类型
	RiskLevel       string  `json:"riskLevel"`       // 风险等级
	ProductStatus   string  `json:"productStatus"`   // 产品状态
	TotalShares     float64 `json:"totalShares"`     // 总持仓份额
	AvailableShares float64 `json:"availableShares"` // 可用持仓份额
	FrozenShares    float64 `json:"frozenShares"`    // 冻结份额
	AverageCost     float64 `json:"averageCost"`     // 平均成本
	LatestNetValue  float64 `json:"latestNetValue"`  // 最新净值
	MarketValue     float64 `json:"marketValue"`     // 持仓市值
	CostValue       float64 `json:"costValue"`       // 持仓成本
	ProfitLoss      float64 `json:"profitLoss"`      // 浮动盈亏
	ProfitLossRate  float64 `json:"profitLossRate"`  // 盈亏比例
	HoldingDays     int64   `json:"holdingDays"`     // 持有天数
}

type CustomerProductsResp struct {
	CustomerId       string                    `json:"customerId"`       // 客户标识
	CustomerName     string                    `json:"customerName"`     // 客户姓名
	TotalProducts    int64                     `json:"totalProducts"`    // 持有产品总数
	TotalMarketValue float64                   `json:"totalMarketValue"` // 总持仓市值
	TotalProfitLoss  float64                   `json:"totalProfitLoss"`  // 总浮动盈亏
	Products         []CustomerProductPosition `json:"products"`         // 产品持仓列表
}

type FailedApplication struct {
	ApplicationId string `json:"applicationId"`
	ErrorReason   string `json:"errorReason"`
	CustomerId    string `json:"customerId"`
	ProductId     string `json:"productId"`
}

type GetCustomerProductsReq struct {
	CustomerId string `path:"customerId"` // 客户标识
}

type GetPositionSummaryReq struct {
	CustomerId string `json:"customerId"`
}

type PageResponse struct {
	Total   int64       `json:"total"`
	Records interface{} `json:"records"`
	Page    int64       `json:"page"`
	Size    int64       `json:"size"`
}

type PositionSummary struct {
	CustomerId        string  `json:"customerId"`        // 客户标识
	CustomerName      string  `json:"customerName"`      // 客户姓名
	TotalPositions    int64   `json:"totalPositions"`    // 总持仓记录数
	TotalProducts     int64   `json:"totalProducts"`     // 持有产品数
	TotalCards        int64   `json:"totalCards"`        // 涉及银行卡数
	TotalMarketValue  float64 `json:"totalMarketValue"`  // 总持仓市值
	TotalCost         float64 `json:"totalCost"`         // 总持仓成本
	TotalProfitLoss   float64 `json:"totalProfitLoss"`   // 总浮动盈亏
	AvgProfitLossRate float64 `json:"avgProfitLossRate"` // 平均盈亏比例
}

type PurchaseRequest struct {
	CustomerId    string  `json:"customerId" validate:"required"`
	ProductId     string  `json:"productId" validate:"required"`
	CardId        int64   `json:"cardId" validate:"required"`
	Amount        float64 `json:"amount" validate:"required,gt=0"`
	OperatorId    string  `json:"operatorId" validate:"required"`
	RiskConfirmed bool    `json:"riskConfirmed,optional"` // 风险不匹配时客户确认
}

type PurchaseResponse struct {
	ApplicationId   string  `json:"applicationId"`
	ApplicationDate string  `json:"applicationDate"`
	ApplicationTime string  `json:"applicationTime"`
	ExpectedDate    string  `json:"expectedDate"`
	Status          string  `json:"status"`
	Amount          float64 `json:"amount"`
	PurchaseFee     float64 `json:"purchaseFee,optional"`
	NetAmount       float64 `json:"netAmount,optional"`
}

type RedemptionRequest struct {
	CustomerId string  `json:"customerId" validate:"required"`
	ProductId  string  `json:"productId" validate:"required"`
	CardId     int64   `json:"cardId" validate:"required"`
	Shares     float64 `json:"shares" validate:"required,gt=0"`
	OperatorId string  `json:"operatorId" validate:"required"`
}

type RedemptionResponse struct {
	ApplicationId   string  `json:"applicationId"`
	ApplicationDate string  `json:"applicationDate"`
	ApplicationTime string  `json:"applicationTime"`
	ExpectedDate    string  `json:"expectedDate"`
	Status          string  `json:"status"`
	Shares          float64 `json:"shares"`
	ExpectedAmount  float64 `json:"expectedAmount,optional"`
	RedemptionFee   float64 `json:"redemptionFee,optional"`
}

type TransactionDetail struct {
	ApplicationId    string  `json:"applicationId"`
	Type             string  `json:"type"`
	CustomerId       string  `json:"customerId"`
	CustomerName     string  `json:"customerName"`
	ProductId        string  `json:"productId"`
	ProductName      string  `json:"productName"`
	ApplicationDate  string  `json:"applicationDate"`
	ApplicationTime  string  `json:"applicationTime"`
	ConfirmationDate string  `json:"confirmationDate,optional"`
	Status           string  `json:"status"`
	OperatorId       string  `json:"operatorId"`
	Amount           float64 `json:"amount,optional"`
	PurchaseFee      float64 `json:"purchaseFee,optional"`
	NetAmount        float64 `json:"netAmount,optional"`
	ConfirmedShares  float64 `json:"confirmedShares,optional"`
	Shares           float64 `json:"shares,optional"`
	ExpectedAmount   float64 `json:"expectedAmount,optional"`
	RedemptionFee    float64 `json:"redemptionFee,optional"`
	HoldingPeriod    int64   `json:"holdingPeriod,optional"`
	ConfirmedAmount  float64 `json:"confirmedAmount,optional"`
	NetValue         float64 `json:"netValue,optional"` // 确认时使用的净值
	ConfirmationId   string  `json:"confirmationId,optional"`
	CreateTime       string  `json:"createTime"`
	UpdateTime       string  `json:"updateTime"`
}

type TransactionQuery struct {
	ApplicationId string `form:"applicationId,optional"`
	CustomerId    string `form:"customerId,optional"`
	ProductId     string `form:"productId,optional"`
	StartDate     string `form:"startDate,optional"`
	EndDate       string `form:"endDate,optional"`
	Type          string `form:"type,optional" validate:"omitempty,oneof=PURCHASE REDEMPTION"`
	Status        string `form:"status,optional"`
	Page          int64  `form:"page,optional,default=1"`
	Size          int64  `form:"size,optional,default=20"`
}

type TransactionRecord struct {
	ApplicationId    string  `json:"applicationId"`
	Type             string  `json:"type"` // PURCHASE, REDEMPTION
	CustomerId       string  `json:"customerId"`
	CustomerName     string  `json:"customerName"`
	ProductId        string  `json:"productId"`
	ProductName      string  `json:"productName"`
	Amount           float64 `json:"amount,optional"`
	Shares           float64 `json:"shares,optional"`
	ApplicationDate  string  `json:"applicationDate"`
	ApplicationTime  string  `json:"applicationTime"`
	ConfirmationDate string  `json:"confirmationDate,optional"`
	Status           string  `json:"status"`
	OperatorId       string  `json:"operatorId"`
}
