// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AffectedRecords struct {
	Quotations    int64 `json:"quotations"`
	Confirmations int64 `json:"confirmations"`
	Positions     int64 `json:"positions"`
	Applications  int64 `json:"applications"`
}

type BaseResponse struct {
	Code    int64       `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type FailedApplicationDetail struct {
	ApplicationId string `json:"applicationId"`
	FailureReason string `json:"failureReason"`
	CustomerId    string `json:"customerId"`
	ProductId     string `json:"productId"`
}

type FailedTransactionDetail struct {
	ConfirmationId string `json:"confirmationId"`
	Reason         string `json:"reason"`
}

type LiquidationLogRecord struct {
	LogId           int64       `json:"logId"`
	LiquidationDate string      `json:"liquidationDate"`
	LiquidationStep string      `json:"liquidationStep"`
	StepStatus      string      `json:"stepStatus"`
	StartTime       string      `json:"startTime,optional"`
	EndTime         string      `json:"endTime,optional"`
	Duration        int64       `json:"duration,optional"`
	ProcessedCount  int64       `json:"processedCount"`
	FailureCount    int64       `json:"failureCount"`
	FailureDetail   interface{} `json:"failureDetail,optional"`
	OperatorId      string      `json:"operatorId"`
	CreateTime      string      `json:"createTime"`
	StepDetails     interface{} `json:"stepDetails,optional"`
}

type LiquidationLogRequest struct {
	LiquidationDate string `form:"liquidationDate,optional"`
	LiquidationStep string `form:"liquidationStep,optional"`
	StepStatus      string `form:"stepStatus,optional"`
	StartTime       string `form:"startTime,optional"`
	EndTime         string `form:"endTime,optional"`
	OperatorId      string `form:"operatorId,optional"`
	Page            int64  `form:"page,optional,default=1"`
	Size            int64  `form:"size,optional,default=50"`
}

type LiquidationLogResponse struct {
	Total   int64                  `json:"total"`
	Records []LiquidationLogRecord `json:"records"`
}

type LiquidationRollbackRequest struct {
	OperatorId      string   `json:"operatorId"`
	LiquidationDate string   `json:"liquidationDate"`
	RollbackType    string   `json:"rollbackType"`
	RollbackSteps   []string `json:"rollbackSteps,optional"`
	Reason          string   `json:"reason"`
	Password        string   `json:"password"`
}

type LiquidationRollbackResponse struct {
	RollbackId      string          `json:"rollbackId"`
	LiquidationDate string          `json:"liquidationDate"`
	RollbackTime    string          `json:"rollbackTime"`
	OperatorId      string          `json:"operatorId"`
	RollbackReason  string          `json:"rollbackReason"`
	AffectedRecords AffectedRecords `json:"affectedRecords"`
	RollbackLogId   int64           `json:"rollbackLogId"`
}

type LiquidationStepItem struct {
	Step      string `json:"step"`
	Status    string `json:"status"`
	StartTime string `json:"startTime,optional"`
	EndTime   string `json:"endTime,optional"`
	Duration  string `json:"duration,optional"`
}

type LiquidationStepStatistics struct {
	LiquidationDate string                `json:"liquidationDate"`
	TotalSteps      int64                 `json:"totalSteps"`
	CompletedSteps  int64                 `json:"completedSteps"`
	PendingSteps    int64                 `json:"pendingSteps"`
	FailedSteps     int64                 `json:"failedSteps"`
	Steps           []LiquidationStepItem `json:"steps"`
}

type NetValuePageResponse struct {
	Total   int64            `json:"total"`
	Records []NetValueRecord `json:"records"`
}

type NetValueQueryRequest struct {
	ProductId string `form:"productId,optional"`
	Page      int64  `form:"page,optional,default=1"`
	Size      int64  `form:"size,optional,default=20"`
	StartDate string `form:"startDate,optional"`
	EndDate   string `form:"endDate,optional"`
}

type NetValueRecord struct {
	ProductId          string  `json:"productId"`
	ProductName        string  `json:"productName"`
	StatDate           string  `json:"statDate"`
	UnitNetValue       float64 `json:"unitNetValue"`
	CumulativeNetValue float64 `json:"cumulativeNetValue"`
	DailyGrowthRate    float64 `json:"dailyGrowthRate"`
	PreviousNetValue   float64 `json:"previousNetValue"`
	GrowthAmount       float64 `json:"growthAmount"`
}

type PageRequest struct {
	Page     int64 `form:"page,optional,default=1"`
	PageSize int64 `form:"size,optional,default=20"`
}

type PendingTransactionRecord struct {
	ApplicationId     string  `json:"applicationId"`
	ApplicationType   string  `json:"applicationType"`
	CustomerId        string  `json:"customerId"`
	CustomerName      string  `json:"customerName"`
	ProductId         string  `json:"productId"`
	ProductName       string  `json:"productName"`
	ApplicationAmount float64 `json:"applicationAmount,optional"`
	ApplicationShares float64 `json:"applicationShares,optional"`
	ApplicationDate   string  `json:"applicationDate"`
	ApplicationStatus string  `json:"applicationStatus"`
	RiskLevel         string  `json:"riskLevel"`
	ProductRiskLevel  string  `json:"productRiskLevel"`
	RiskMatch         bool    `json:"riskMatch"`
}

type PendingTransactionRequest struct {
	ApplicationDate string `form:"applicationDate"`
	ApplicationType string `form:"applicationType,optional"`
	ProductId       string `form:"productId,optional"`
	CustomerId      string `form:"customerId,optional"`
	Page            int64  `form:"page,optional,default=1"`
	Size            int64  `form:"size,optional,default=50"`
}

type PendingTransactionResponse struct {
	Total   int64                      `json:"total"`
	Records []PendingTransactionRecord `json:"records"`
}

type QuotationUpdateRequest struct {
	OperatorId    string   `json:"operatorId"`
	QuotationDate string   `json:"quotationDate,optional"`
	ProductIds    []string `json:"productIds,optional"`
	UpdateMethod  string   `json:"updateMethod"`
}

type QuotationUpdateResponse struct {
	QuotationDate  string   `json:"quotationDate"`
	UpdatedCount   int64    `json:"updatedCount"`
	FailedCount    int64    `json:"failedCount"`
	FailedProducts []string `json:"failedProducts"`
	LogId          int64    `json:"logId"`
}

type RetryFailedTransactionRequest struct {
	OperatorId      string   `json:"operatorId"`
	ConfirmationIds []string `json:"confirmationIds"`
	ForceRetry      bool     `json:"forceRetry,optional"`
}

type RetryFailedTransactionResponse struct {
	TotalRetry    int64                     `json:"totalRetry"`
	SuccessCount  int64                     `json:"successCount"`
	FailedCount   int64                     `json:"failedCount"`
	SuccessIds    []string                  `json:"successIds"`
	FailedDetails []FailedTransactionDetail `json:"failedDetails"`
}

type TradingDayInitRequest struct {
	OperatorId  string `json:"operatorId"`
	ForceUpdate bool   `json:"forceUpdate,optional"`
	TargetDate  string `json:"targetDate,optional"`
}

type TradingDayInitResponse struct {
	PreviousTradingDay string `json:"previousTradingDay"`
	CurrentTradingDay  string `json:"currentTradingDay"`
	NextTradingDay     string `json:"nextTradingDay"`
	InitTime           string `json:"initTime"`
	LogId              int64  `json:"logId"`
}

type TradingDayResponse struct {
	TradingDay         string `json:"tradingDay"`
	IsWorkday          bool   `json:"isWorkday"`
	WorkdayType        string `json:"workdayType"`
	PreviousTradingDay string `json:"previousTradingDay"`
	NextTradingDay     string `json:"nextTradingDay"`
}

type TransactionConfirmRequest struct {
	OperatorId       string   `json:"operatorId"`
	ConfirmationDate string   `json:"confirmationDate,optional"`
	ApplicationType  string   `json:"applicationType"`
	ApplicationIds   []string `json:"applicationIds,optional"`
	BatchSize        int64    `json:"batchSize,optional,default=100"`
}

type TransactionConfirmResponse struct {
	ConfirmationDate   string                    `json:"confirmationDate"`
	TotalApplications  int64                     `json:"totalApplications"`
	SuccessCount       int64                     `json:"successCount"`
	FailedCount        int64                     `json:"failedCount"`
	ConfirmedAmount    float64                   `json:"confirmedAmount"`
	ConfirmedShares    float64                   `json:"confirmedShares"`
	TotalFees          float64                   `json:"totalFees"`
	ConfirmationIds    []string                  `json:"confirmationIds"`
	LogId              int64                     `json:"logId"`
	FailedApplications []FailedApplicationDetail `json:"failedApplications"`
}
