// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	customerPositionFieldNames          = builder.RawFieldNames(&CustomerPosition{})
	customerPositionRows                = strings.Join(customerPositionFieldNames, ",")
	customerPositionRowsExpectAutoSet   = strings.Join(stringx.Remove(customerPositionFieldNames, "`position_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	customerPositionRowsWithPlaceHolder = strings.Join(stringx.Remove(customerPositionFieldNames, "`position_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	customerPositionModel interface {
		Insert(ctx context.Context, data *CustomerPosition) (sql.Result, error)
		FindOne(ctx context.Context, positionId int64) (*CustomerPosition, error)
		FindOneByCustomerIdProductIdCardId(ctx context.Context, customerId string, productId string, cardId int64) (*CustomerPosition, error)
		Update(ctx context.Context, data *CustomerPosition) error
		Delete(ctx context.Context, positionId int64) error
	}

	defaultCustomerPositionModel struct {
		conn  sqlx.SqlConn
		table string
	}

	CustomerPosition struct {
		PositionId      int64           `db:"position_id"`      // 持仓记录唯一标识
		CustomerId      string          `db:"customer_id"`      // 客户标识
		ProductId       string          `db:"product_id"`       // 产品标识
		CardId          int64           `db:"card_id"`          // 银行卡标识
		TotalShares     float64         `db:"total_shares"`     // 总持仓份额
		AvailableShares float64         `db:"available_shares"` // 可用持仓份额
		FrozenShares    float64         `db:"frozen_shares"`    // 冻结份额
		AverageCost     sql.NullFloat64 `db:"average_cost"`     // 持仓平均成本
		PositionDate    time.Time       `db:"position_date"`    // 持仓统计日期
		CreateTime      time.Time       `db:"create_time"`      // 持仓创建时间
		UpdateTime      time.Time       `db:"update_time"`      // 持仓更新时间
	}
)

func newCustomerPositionModel(conn sqlx.SqlConn) *defaultCustomerPositionModel {
	return &defaultCustomerPositionModel{
		conn:  conn,
		table: "`customer_position`",
	}
}

func (m *defaultCustomerPositionModel) Delete(ctx context.Context, positionId int64) error {
	query := fmt.Sprintf("delete from %s where `position_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, positionId)
	return err
}

func (m *defaultCustomerPositionModel) FindOne(ctx context.Context, positionId int64) (*CustomerPosition, error) {
	query := fmt.Sprintf("select %s from %s where `position_id` = ? limit 1", customerPositionRows, m.table)
	var resp CustomerPosition
	err := m.conn.QueryRowCtx(ctx, &resp, query, positionId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCustomerPositionModel) FindOneByCustomerIdProductIdCardId(ctx context.Context, customerId string, productId string, cardId int64) (*CustomerPosition, error) {
	var resp CustomerPosition
	query := fmt.Sprintf("select %s from %s where `customer_id` = ? and `product_id` = ? and `card_id` = ? limit 1", customerPositionRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, customerId, productId, cardId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCustomerPositionModel) Insert(ctx context.Context, data *CustomerPosition) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, customerPositionRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.CustomerId, data.ProductId, data.CardId, data.TotalShares, data.AvailableShares, data.FrozenShares, data.AverageCost, data.PositionDate)
	return ret, err
}

func (m *defaultCustomerPositionModel) Update(ctx context.Context, newData *CustomerPosition) error {
	query := fmt.Sprintf("update %s set %s where `position_id` = ?", m.table, customerPositionRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.CustomerId, newData.ProductId, newData.CardId, newData.TotalShares, newData.AvailableShares, newData.FrozenShares, newData.AverageCost, newData.PositionDate, newData.PositionId)
	return err
}

func (m *defaultCustomerPositionModel) tableName() string {
	return m.table
}
