// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	liquidationLogFieldNames          = builder.RawFieldNames(&LiquidationLog{})
	liquidationLogRows                = strings.Join(liquidationLogFieldNames, ",")
	liquidationLogRowsExpectAutoSet   = strings.Join(stringx.Remove(liquidationLogFieldNames, "`log_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	liquidationLogRowsWithPlaceHolder = strings.Join(stringx.Remove(liquidationLogFieldNames, "`log_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	liquidationLogModel interface {
		Insert(ctx context.Context, data *LiquidationLog) (sql.Result, error)
		FindOne(ctx context.Context, logId int64) (*LiquidationLog, error)
		Update(ctx context.Context, data *LiquidationLog) error
		Delete(ctx context.Context, logId int64) error
	}

	defaultLiquidationLogModel struct {
		conn  sqlx.SqlConn
		table string
	}

	LiquidationLog struct {
		LogId           int64          `db:"log_id"`           // 日志记录唯一标识
		LiquidationDate time.Time      `db:"liquidation_date"` // 清算日期（T+1日）
		LiquidationStep string         `db:"liquidation_step"` // 清算步骤
		StepStatus      string         `db:"step_status"`      // 步骤状态
		StartTime       sql.NullTime   `db:"start_time"`       // 步骤开始时间
		EndTime         sql.NullTime   `db:"end_time"`         // 步骤结束时间
		ProcessedCount  int64          `db:"processed_count"`  // 处理记录数
		FailureCount    int64          `db:"failure_count"`    // 失败记录数
		FailureDetail   sql.NullString `db:"failure_detail"`   // 失败详情
		OperatorId      sql.NullString `db:"operator_id"`      // 操作员ID
		CreateTime      time.Time      `db:"create_time"`      // 日志创建时间
	}
)

func newLiquidationLogModel(conn sqlx.SqlConn) *defaultLiquidationLogModel {
	return &defaultLiquidationLogModel{
		conn:  conn,
		table: "`liquidation_log`",
	}
}

func (m *defaultLiquidationLogModel) Delete(ctx context.Context, logId int64) error {
	query := fmt.Sprintf("delete from %s where `log_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, logId)
	return err
}

func (m *defaultLiquidationLogModel) FindOne(ctx context.Context, logId int64) (*LiquidationLog, error) {
	query := fmt.Sprintf("select %s from %s where `log_id` = ? limit 1", liquidationLogRows, m.table)
	var resp LiquidationLog
	err := m.conn.QueryRowCtx(ctx, &resp, query, logId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLiquidationLogModel) Insert(ctx context.Context, data *LiquidationLog) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, liquidationLogRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.LiquidationDate, data.LiquidationStep, data.StepStatus, data.StartTime, data.EndTime, data.ProcessedCount, data.FailureCount, data.FailureDetail, data.OperatorId)
	return ret, err
}

func (m *defaultLiquidationLogModel) Update(ctx context.Context, data *LiquidationLog) error {
	query := fmt.Sprintf("update %s set %s where `log_id` = ?", m.table, liquidationLogRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.LiquidationDate, data.LiquidationStep, data.StepStatus, data.StartTime, data.EndTime, data.ProcessedCount, data.FailureCount, data.FailureDetail, data.OperatorId, data.LogId)
	return err
}

func (m *defaultLiquidationLogModel) tableName() string {
	return m.table
}
