// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	workCalendarFieldNames          = builder.RawFieldNames(&WorkCalendar{})
	workCalendarRows                = strings.Join(workCalendarFieldNames, ",")
	workCalendarRowsExpectAutoSet   = strings.Join(stringx.Remove(workCalendarFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	workCalendarRowsWithPlaceHolder = strings.Join(stringx.Remove(workCalendarFieldNames, "`calendar_date`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	workCalendarModel interface {
		Insert(ctx context.Context, data *WorkCalendar) (sql.Result, error)
		FindOne(ctx context.Context, calendarDate time.Time) (*WorkCalendar, error)
		Update(ctx context.Context, data *WorkCalendar) error
		Delete(ctx context.Context, calendarDate time.Time) error
	}

	defaultWorkCalendarModel struct {
		conn  sqlx.SqlConn
		table string
	}

	WorkCalendar struct {
		CalendarDate time.Time      `db:"calendar_date"` // 日期
		IsWorkday    int64          `db:"is_workday"`    // 是否工作日，1-是，0-否
		WorkdayType  string         `db:"workday_type"`  // 工作日类型
		Remark       sql.NullString `db:"remark"`        // 备注
		CreateTime   time.Time      `db:"create_time"`   // 记录创建时间
		UpdateTime   time.Time      `db:"update_time"`   // 记录更新时间
	}
)

func newWorkCalendarModel(conn sqlx.SqlConn) *defaultWorkCalendarModel {
	return &defaultWorkCalendarModel{
		conn:  conn,
		table: "`work_calendar`",
	}
}

func (m *defaultWorkCalendarModel) Delete(ctx context.Context, calendarDate time.Time) error {
	query := fmt.Sprintf("delete from %s where `calendar_date` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, calendarDate)
	return err
}

func (m *defaultWorkCalendarModel) FindOne(ctx context.Context, calendarDate time.Time) (*WorkCalendar, error) {
	query := fmt.Sprintf("select %s from %s where `calendar_date` = ? limit 1", workCalendarRows, m.table)
	var resp WorkCalendar
	err := m.conn.QueryRowCtx(ctx, &resp, query, calendarDate)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWorkCalendarModel) Insert(ctx context.Context, data *WorkCalendar) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, workCalendarRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.CalendarDate, data.IsWorkday, data.WorkdayType, data.Remark)
	return ret, err
}

func (m *defaultWorkCalendarModel) Update(ctx context.Context, data *WorkCalendar) error {
	query := fmt.Sprintf("update %s set %s where `calendar_date` = ?", m.table, workCalendarRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.IsWorkday, data.WorkdayType, data.Remark, data.CalendarDate)
	return err
}

func (m *defaultWorkCalendarModel) tableName() string {
	return m.table
}
