// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	productNetValueFieldNames          = builder.RawFieldNames(&ProductNetValue{})
	productNetValueRows                = strings.Join(productNetValueFieldNames, ",")
	productNetValueRowsExpectAutoSet   = strings.Join(stringx.Remove(productNetValueFieldNames, "`net_value_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	productNetValueRowsWithPlaceHolder = strings.Join(stringx.Remove(productNetValueFieldNames, "`net_value_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	productNetValueModel interface {
		Insert(ctx context.Context, data *ProductNetValue) (sql.Result, error)
		FindOne(ctx context.Context, netValueId int64) (*ProductNetValue, error)
		FindOneByProductIdStatDate(ctx context.Context, productId string, statDate time.Time) (*ProductNetValue, error)
		Update(ctx context.Context, data *ProductNetValue) error
		Delete(ctx context.Context, netValueId int64) error
	}

	defaultProductNetValueModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ProductNetValue struct {
		NetValueId         int64           `db:"net_value_id"`         // 净值记录唯一标识
		ProductId          string          `db:"product_id"`           // 产品标识
		StatDate           time.Time       `db:"stat_date"`            // 净值统计日期
		UnitNetValue       float64         `db:"unit_net_value"`       // 单位净值
		CumulativeNetValue float64         `db:"cumulative_net_value"` // 累计净值
		DailyGrowthRate    sql.NullFloat64 `db:"daily_growth_rate"`    // 日增长率
		CreateTime         time.Time       `db:"create_time"`          // 记录创建时间
	}
)

func newProductNetValueModel(conn sqlx.SqlConn) *defaultProductNetValueModel {
	return &defaultProductNetValueModel{
		conn:  conn,
		table: "`product_net_value`",
	}
}

func (m *defaultProductNetValueModel) Delete(ctx context.Context, netValueId int64) error {
	query := fmt.Sprintf("delete from %s where `net_value_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, netValueId)
	return err
}

func (m *defaultProductNetValueModel) FindOne(ctx context.Context, netValueId int64) (*ProductNetValue, error) {
	query := fmt.Sprintf("select %s from %s where `net_value_id` = ? limit 1", productNetValueRows, m.table)
	var resp ProductNetValue
	err := m.conn.QueryRowCtx(ctx, &resp, query, netValueId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProductNetValueModel) FindOneByProductIdStatDate(ctx context.Context, productId string, statDate time.Time) (*ProductNetValue, error) {
	var resp ProductNetValue
	query := fmt.Sprintf("select %s from %s where `product_id` = ? and `stat_date` = ? limit 1", productNetValueRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, productId, statDate)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProductNetValueModel) Insert(ctx context.Context, data *ProductNetValue) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, productNetValueRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ProductId, data.StatDate, data.UnitNetValue, data.CumulativeNetValue, data.DailyGrowthRate)
	return ret, err
}

func (m *defaultProductNetValueModel) Update(ctx context.Context, newData *ProductNetValue) error {
	query := fmt.Sprintf("update %s set %s where `net_value_id` = ?", m.table, productNetValueRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.ProductId, newData.StatDate, newData.UnitNetValue, newData.CumulativeNetValue, newData.DailyGrowthRate, newData.NetValueId)
	return err
}

func (m *defaultProductNetValueModel) tableName() string {
	return m.table
}
