// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	productInfoFieldNames          = builder.RawFieldNames(&ProductInfo{})
	productInfoRows                = strings.Join(productInfoFieldNames, ",")
	productInfoRowsExpectAutoSet   = strings.Join(stringx.Remove(productInfoFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	productInfoRowsWithPlaceHolder = strings.Join(stringx.Remove(productInfoFieldNames, "`product_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	productInfoModel interface {
		Insert(ctx context.Context, data *ProductInfo) (sql.Result, error)
		FindOne(ctx context.Context, productId string) (*ProductInfo, error)
		Update(ctx context.Context, data *ProductInfo) error
		Delete(ctx context.Context, productId string) error
	}

	defaultProductInfoModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ProductInfo struct {
		ProductId         string          `db:"product_id"`          // 产品唯一标识
		ProductName       string          `db:"product_name"`        // 产品名称
		ProductType       string          `db:"product_type"`        // 产品类型
		ProductSubType    sql.NullString  `db:"product_sub_type"`    // 产品子类型
		RiskLevel         string          `db:"risk_level"`          // 产品风险等级
		ProductStatus     string          `db:"product_status"`      // 产品状态
		Manager           string          `db:"manager"`             // 基金管理人
		Custodian         string          `db:"custodian"`           // 基金托管人
		PurchaseFeeRate   sql.NullFloat64 `db:"purchase_fee_rate"`   // 前端申购费率
		RedemptionFeeRule sql.NullString  `db:"redemption_fee_rule"` // 赎回费率规则
		Description       sql.NullString  `db:"description"`         // 产品说明书
		CreateTime        time.Time       `db:"create_time"`         // 产品创建时间
		UpdateTime        time.Time       `db:"update_time"`         // 产品信息更新时间
	}
)

func newProductInfoModel(conn sqlx.SqlConn) *defaultProductInfoModel {
	return &defaultProductInfoModel{
		conn:  conn,
		table: "`product_info`",
	}
}

func (m *defaultProductInfoModel) Delete(ctx context.Context, productId string) error {
	query := fmt.Sprintf("delete from %s where `product_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, productId)
	return err
}

func (m *defaultProductInfoModel) FindOne(ctx context.Context, productId string) (*ProductInfo, error) {
	query := fmt.Sprintf("select %s from %s where `product_id` = ? limit 1", productInfoRows, m.table)
	var resp ProductInfo
	err := m.conn.QueryRowCtx(ctx, &resp, query, productId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProductInfoModel) Insert(ctx context.Context, data *ProductInfo) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, productInfoRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ProductId, data.ProductName, data.ProductType, data.ProductSubType, data.RiskLevel, data.ProductStatus, data.Manager, data.Custodian, data.PurchaseFeeRate, data.RedemptionFeeRule, data.Description)
	return ret, err
}

func (m *defaultProductInfoModel) Update(ctx context.Context, data *ProductInfo) error {
	query := fmt.Sprintf("update %s set %s where `product_id` = ?", m.table, productInfoRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ProductName, data.ProductType, data.ProductSubType, data.RiskLevel, data.ProductStatus, data.Manager, data.Custodian, data.PurchaseFeeRate, data.RedemptionFeeRule, data.Description, data.ProductId)
	return err
}

func (m *defaultProductInfoModel) tableName() string {
	return m.table
}
