// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	purchaseApplicationFieldNames          = builder.RawFieldNames(&PurchaseApplication{})
	purchaseApplicationRows                = strings.Join(purchaseApplicationFieldNames, ",")
	purchaseApplicationRowsExpectAutoSet   = strings.Join(stringx.Remove(purchaseApplicationFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	purchaseApplicationRowsWithPlaceHolder = strings.Join(stringx.Remove(purchaseApplicationFieldNames, "`application_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	purchaseApplicationModel interface {
		Insert(ctx context.Context, data *PurchaseApplication) (sql.Result, error)
		FindOne(ctx context.Context, applicationId string) (*PurchaseApplication, error)
		Update(ctx context.Context, data *PurchaseApplication) error
		Delete(ctx context.Context, applicationId string) error
	}

	defaultPurchaseApplicationModel struct {
		conn  sqlx.SqlConn
		table string
	}

	PurchaseApplication struct {
		ApplicationId            string          `db:"application_id"`             // 申购申请编号
		CustomerId               string          `db:"customer_id"`                // 客户标识
		ProductId                string          `db:"product_id"`                 // 产品标识
		CardId                   int64           `db:"card_id"`                    // 银行卡标识
		ApplicationAmount        float64         `db:"application_amount"`         // 申购金额
		PurchaseFee              sql.NullFloat64 `db:"purchase_fee"`               // 申购费用
		NetPurchaseAmount        sql.NullFloat64 `db:"net_purchase_amount"`        // 净申购金额
		ApplicationDate          time.Time       `db:"application_date"`           // 申购申请日期（T日）
		ApplicationTime          time.Time       `db:"application_time"`           // 申购申请时间
		ExpectedConfirmationDate time.Time       `db:"expected_confirmation_date"` // 预计确认日期（默认T+1）
		ApplicationStatus        string          `db:"application_status"`         // 申请状态
		RiskMismatchRemark       sql.NullString  `db:"risk_mismatch_remark"`       // 风险等级不匹配备注
		OperatorId               string          `db:"operator_id"`                // 操作员ID
		CreateTime               time.Time       `db:"create_time"`                // 记录创建时间
		UpdateTime               time.Time       `db:"update_time"`                // 记录更新时间
	}
)

func newPurchaseApplicationModel(conn sqlx.SqlConn) *defaultPurchaseApplicationModel {
	return &defaultPurchaseApplicationModel{
		conn:  conn,
		table: "`purchase_application`",
	}
}

func (m *defaultPurchaseApplicationModel) Delete(ctx context.Context, applicationId string) error {
	query := fmt.Sprintf("delete from %s where `application_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, applicationId)
	return err
}

func (m *defaultPurchaseApplicationModel) FindOne(ctx context.Context, applicationId string) (*PurchaseApplication, error) {
	query := fmt.Sprintf("select %s from %s where `application_id` = ? limit 1", purchaseApplicationRows, m.table)
	var resp PurchaseApplication
	err := m.conn.QueryRowCtx(ctx, &resp, query, applicationId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPurchaseApplicationModel) Insert(ctx context.Context, data *PurchaseApplication) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, purchaseApplicationRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ApplicationId, data.CustomerId, data.ProductId, data.CardId, data.ApplicationAmount, data.PurchaseFee, data.NetPurchaseAmount, data.ApplicationDate, data.ApplicationTime, data.ExpectedConfirmationDate, data.ApplicationStatus, data.RiskMismatchRemark, data.OperatorId)
	return ret, err
}

func (m *defaultPurchaseApplicationModel) Update(ctx context.Context, data *PurchaseApplication) error {
	query := fmt.Sprintf("update %s set %s where `application_id` = ?", m.table, purchaseApplicationRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.CustomerId, data.ProductId, data.CardId, data.ApplicationAmount, data.PurchaseFee, data.NetPurchaseAmount, data.ApplicationDate, data.ApplicationTime, data.ExpectedConfirmationDate, data.ApplicationStatus, data.RiskMismatchRemark, data.OperatorId, data.ApplicationId)
	return err
}

func (m *defaultPurchaseApplicationModel) tableName() string {
	return m.table
}
