// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	redemptionApplicationFieldNames          = builder.RawFieldNames(&RedemptionApplication{})
	redemptionApplicationRows                = strings.Join(redemptionApplicationFieldNames, ",")
	redemptionApplicationRowsExpectAutoSet   = strings.Join(stringx.Remove(redemptionApplicationFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	redemptionApplicationRowsWithPlaceHolder = strings.Join(stringx.Remove(redemptionApplicationFieldNames, "`application_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	redemptionApplicationModel interface {
		Insert(ctx context.Context, data *RedemptionApplication) (sql.Result, error)
		FindOne(ctx context.Context, applicationId string) (*RedemptionApplication, error)
		Update(ctx context.Context, data *RedemptionApplication) error
		Delete(ctx context.Context, applicationId string) error
	}

	defaultRedemptionApplicationModel struct {
		conn  sqlx.SqlConn
		table string
	}

	RedemptionApplication struct {
		ApplicationId            string          `db:"application_id"`             // 赎回申请编号
		CustomerId               string          `db:"customer_id"`                // 客户标识
		ProductId                string          `db:"product_id"`                 // 产品标识
		CardId                   int64           `db:"card_id"`                    // 银行卡标识
		ApplicationShares        float64         `db:"application_shares"`         // 赎回份额
		HoldingPeriod            sql.NullInt64   `db:"holding_period"`             // 持有期限（天）
		RedemptionFee            sql.NullFloat64 `db:"redemption_fee"`             // 赎回费用
		ExpectedRedemptionAmount sql.NullFloat64 `db:"expected_redemption_amount"` // 预计赎回金额
		ApplicationDate          time.Time       `db:"application_date"`           // 赎回申请日期（T日）
		ApplicationTime          time.Time       `db:"application_time"`           // 赎回申请时间
		ExpectedConfirmationDate time.Time       `db:"expected_confirmation_date"` // 预计确认日期（默认T+1）
		ApplicationStatus        string          `db:"application_status"`         // 申请状态
		OperatorId               string          `db:"operator_id"`                // 操作员ID
		CreateTime               time.Time       `db:"create_time"`                // 记录创建时间
		UpdateTime               time.Time       `db:"update_time"`                // 记录更新时间
	}
)

func newRedemptionApplicationModel(conn sqlx.SqlConn) *defaultRedemptionApplicationModel {
	return &defaultRedemptionApplicationModel{
		conn:  conn,
		table: "`redemption_application`",
	}
}

func (m *defaultRedemptionApplicationModel) Delete(ctx context.Context, applicationId string) error {
	query := fmt.Sprintf("delete from %s where `application_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, applicationId)
	return err
}

func (m *defaultRedemptionApplicationModel) FindOne(ctx context.Context, applicationId string) (*RedemptionApplication, error) {
	query := fmt.Sprintf("select %s from %s where `application_id` = ? limit 1", redemptionApplicationRows, m.table)
	var resp RedemptionApplication
	err := m.conn.QueryRowCtx(ctx, &resp, query, applicationId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRedemptionApplicationModel) Insert(ctx context.Context, data *RedemptionApplication) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, redemptionApplicationRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ApplicationId, data.CustomerId, data.ProductId, data.CardId, data.ApplicationShares, data.HoldingPeriod, data.RedemptionFee, data.ExpectedRedemptionAmount, data.ApplicationDate, data.ApplicationTime, data.ExpectedConfirmationDate, data.ApplicationStatus, data.OperatorId)
	return ret, err
}

func (m *defaultRedemptionApplicationModel) Update(ctx context.Context, data *RedemptionApplication) error {
	query := fmt.Sprintf("update %s set %s where `application_id` = ?", m.table, redemptionApplicationRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.CustomerId, data.ProductId, data.CardId, data.ApplicationShares, data.HoldingPeriod, data.RedemptionFee, data.ExpectedRedemptionAmount, data.ApplicationDate, data.ApplicationTime, data.ExpectedConfirmationDate, data.ApplicationStatus, data.OperatorId, data.ApplicationId)
	return err
}

func (m *defaultRedemptionApplicationModel) tableName() string {
	return m.table
}
