// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	transactionConfirmationFieldNames          = builder.RawFieldNames(&TransactionConfirmation{})
	transactionConfirmationRows                = strings.Join(transactionConfirmationFieldNames, ",")
	transactionConfirmationRowsExpectAutoSet   = strings.Join(stringx.Remove(transactionConfirmationFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	transactionConfirmationRowsWithPlaceHolder = strings.Join(stringx.Remove(transactionConfirmationFieldNames, "`confirmation_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	transactionConfirmationModel interface {
		Insert(ctx context.Context, data *TransactionConfirmation) (sql.Result, error)
		FindOne(ctx context.Context, confirmationId string) (*TransactionConfirmation, error)
		Update(ctx context.Context, data *TransactionConfirmation) error
		Delete(ctx context.Context, confirmationId string) error
	}

	defaultTransactionConfirmationModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TransactionConfirmation struct {
		ConfirmationId     string          `db:"confirmation_id"`     // 确认编号
		ApplicationId      string          `db:"application_id"`      // 申请编号
		TransactionType    string          `db:"transaction_type"`    // 交易类型
		CustomerId         string          `db:"customer_id"`         // 客户标识
		ProductId          string          `db:"product_id"`          // 产品标识
		ConfirmationDate   time.Time       `db:"confirmation_date"`   // 确认日期（T+1日）
		ConfirmedShares    sql.NullFloat64 `db:"confirmed_shares"`    // 确认份额（申购时有效）
		ConfirmedAmount    sql.NullFloat64 `db:"confirmed_amount"`    // 确认金额（赎回时有效）
		NetValue           float64         `db:"net_value"`           // 确认时使用的产品净值
		Fee                sql.NullFloat64 `db:"fee"`                 // 交易费用
		ConfirmationStatus string          `db:"confirmation_status"` // 确认状态
		FailureReason      sql.NullString  `db:"failure_reason"`      // 确认失败原因
		CreateTime         time.Time       `db:"create_time"`         // 确认记录创建时间
	}
)

func newTransactionConfirmationModel(conn sqlx.SqlConn) *defaultTransactionConfirmationModel {
	return &defaultTransactionConfirmationModel{
		conn:  conn,
		table: "`transaction_confirmation`",
	}
}

func (m *defaultTransactionConfirmationModel) Delete(ctx context.Context, confirmationId string) error {
	query := fmt.Sprintf("delete from %s where `confirmation_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, confirmationId)
	return err
}

func (m *defaultTransactionConfirmationModel) FindOne(ctx context.Context, confirmationId string) (*TransactionConfirmation, error) {
	query := fmt.Sprintf("select %s from %s where `confirmation_id` = ? limit 1", transactionConfirmationRows, m.table)
	var resp TransactionConfirmation
	err := m.conn.QueryRowCtx(ctx, &resp, query, confirmationId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTransactionConfirmationModel) Insert(ctx context.Context, data *TransactionConfirmation) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, transactionConfirmationRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ConfirmationId, data.ApplicationId, data.TransactionType, data.CustomerId, data.ProductId, data.ConfirmationDate, data.ConfirmedShares, data.ConfirmedAmount, data.NetValue, data.Fee, data.ConfirmationStatus, data.FailureReason)
	return ret, err
}

func (m *defaultTransactionConfirmationModel) Update(ctx context.Context, data *TransactionConfirmation) error {
	query := fmt.Sprintf("update %s set %s where `confirmation_id` = ?", m.table, transactionConfirmationRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ApplicationId, data.TransactionType, data.CustomerId, data.ProductId, data.ConfirmationDate, data.ConfirmedShares, data.ConfirmedAmount, data.NetValue, data.Fee, data.ConfirmationStatus, data.FailureReason, data.ConfirmationId)
	return err
}

func (m *defaultTransactionConfirmationModel) tableName() string {
	return m.table
}
