// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	trade "WMSS/trade/api/internal/handler/trade"
	"WMSS/trade/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/trade/cancel",
				Handler: trade.CancelTransactionHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/trade/confirm",
				Handler: trade.ConfirmTransactionsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/trade/customer/:customerId/products",
				Handler: trade.GetCustomerProductsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/trade/positions/summary",
				Handler: trade.GetPositionSummaryHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/trade/purchase",
				Handler: trade.ApplyPurchaseHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/trade/redemption",
				Handler: trade.ApplyRedemptionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/trade/transactions",
				Handler: trade.QueryTransactionsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/trade/transactions/:applicationId",
				Handler: trade.GetTransactionDetailHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)
}
